function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t770_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t770');var burger=rec.querySelector('.t770__mobile_burger');var logo=menu?menu.querySelector('.t770__imglogo'):null;var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';var isEditMode=menu?menu.classList.contains('t770_redactor-mode'):!1;if(!isEditMode){t770_highlight();if(menu)menu.classList.remove('t770__beforeready');if(menu&&menuPosition==='fixed'){t770_checkAnchorLinks(recid);if(menu.getAttribute('data-bgopacity-two')){t770_changebgopacitymenu(recid);window.addEventListener('scroll',t_throttle(function(){t770_changebgopacitymenu(recid)},200))}
if(menu.getAttribute('data-appearoffset')){menu.classList.remove('t770__beforeready');t770_appearMenu(recid);window.addEventListener('scroll',t_throttle(function(){t770_appearMenu(recid)},200))}}}
if(logo&&logo.getAttribute('data-img-width')){t770_setLogoPadding(recid)}
if(burger){t770_createMobileMenu(recid)}
t770_setBg(recid);window.addEventListener('resize',t_throttle(function(){t770_setBg(recid)},200))}
function t770_setLogoPadding(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t770');var logo=menu?menu.querySelector('.t770__logowrapper'):null;var leftSide=menu?menu.querySelector('.t770__leftwrapper'):null;var rightSide=menu?menu.querySelector('.t770__rightwrapper'):null;var logoWidth=logo?logo.clientWidth:0;if(leftSide)leftSide.style.paddingRight=((logoWidth/2)+50)+'px';if(rightSide)rightSide.style.paddingLeft=((logoWidth/2)+50)+'px'}
function t770_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t770__list_item a[href=\''+url+'\'], '+'.t770__list_item a[href=\''+url+'/\'], '+'.t770__list_item a[href=\''+pathname+'\'], '+'.t770__list_item a[href=\'/'+pathname+'\'], '+'.t770__list_item a[href=\''+pathname+'/\'], '+'.t770__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t770_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t770__desktoplist .t770__list_item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t770_catchScroll(navLinks)}}
function t770_catchScroll(navLinks){var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t770_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t770_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t770_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t770').bind('displayChanged',function(){t770_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t770');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t770_updateSectionsOffsets(sections)})})}
setInterval(function(){t770_updateSectionsOffsets(sections)},5000);t770_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t770_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t770_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t770_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t770_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t770_getSectionByHref(curlink){if(!curlink)return;var curLinkValue=curlink.href?curlink.href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(curlink.href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var recordElements=document.querySelectorAll('.r[data-record-type=\'215\']');recordElements=Array.prototype.filter.call(recordElements,function(element){return element.querySelector('a[name=\''+curLinkValue.slice(1)+'\']')});return recordElements.length?recordElements[0]:null}}
function t770_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t770_setBg(recid){var menuBlocks=document.querySelectorAll('.t770');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t770_appearMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t770');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t770_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t770_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t770_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t770_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t770');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t770_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t770');var burger=rec.querySelector('.t770__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t770_opened')){t770_fadeOut(menu,300);burger.classList.remove('t770_opened')}else{t770_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t770_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu)menu.style.opacity='';if(menu)menu.style.display='';if(burger)burger.classList.remove('t770_opened')}},200))}
function t770_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t770_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t778__init(recid){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t778_initPopup(recid);t778__hoverZoom_init(recid);t778__updateLazyLoad(recid);t778__alignButtons_init(recid);t778__showMore(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t778_initProductQuantity(recid)}
$('body').trigger('twishlist_addbtn')}
function t778_initProductQuantity(recid){var el=$('#rec'+recid);var productList=el.find(".t778__col, .t778__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents($(product))})}
function t778__showMore(recid){var el=$('#rec'+recid).find(".t778");var showmore=el.find('.t778__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t778__dict('loadmore'))}
showmore.show();el.find('.t778__col').hide();var cards_size=el.find('.t778__col').size();var x=cards_count;var y=cards_count;t778__showSeparator(el,x);el.find('.t778__col:lt('+x+')').show();showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t778__col:lt('+x+')').show();el.trigger('displayChanged');if(x==cards_size){showmore.hide()}
t778__showSeparator(el,x);if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t778__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t778__showSeparator(el,x){el.find('.t778__separator_number').addClass('t778__separator_hide');el.find('.t778__separator_hide').each(function(){if($(this).attr('data-product-separator-number')<=x){$(this).removeClass('t778__separator_hide')}})}
function t778__hoverZoom_init(recid){if(window.isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid,".t-slds__container")},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t778__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t778__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t778__alignButtons_init(recid){var el=$('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t778__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&window.isMobile){return}
t778__alignButtons(recid)}));el.find('.t778').bind('displayChanged',function(){t778__alignButtons(recid)});if(window.isMobile){$(window).on('orientationchange',function(){t778__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t778__alignButtons(recid){var rec=$('#rec'+recid);var contents=rec.find('.t778__content');var maxHeight=0;var maxHeightBtns=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t778__container_mobile-flex')[0]?!0:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t778 .mobile-two-columns')[0]?!0:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var textWrappersInRow=[];var btnWrappersInRow=[];$.each(contents,function(key,content){var textWrapper=$(content).find('.t778__textwrapper');if(textWrapper.length>0){textWrapper=textWrapper[0];textWrapper.style.height='auto';if(itemsInRow===1){textWrapper.style.height='auto'}else{textWrappersInRow.push(textWrapper);if(textWrapper.offsetHeight>maxHeight){maxHeight=textWrapper.offsetHeight}
if(maxHeight>0){$(textWrappersInRow).css('height',maxHeight)}}}
var btnWrapper=$(content).find('.t778__btn-wrapper');if(btnWrapper.length>0){btnWrapper=btnWrapper[0];btnWrapper.style.marginTop='';if(itemsInRow===1){btnWrapper.style.marginTop=''}else{btnWrappersInRow.push(btnWrapper);if(btnWrapper.offsetHeight>maxHeightBtns){maxHeightBtns=btnWrapper.offsetHeight}
$.each(btnWrappersInRow,function(key,btn){if(maxHeightBtns>btn.offsetHeight){btn.style.marginTop=(maxHeightBtns-btn.offsetHeight)+'px'}})}}
if(i===itemsInRow){i=0;maxHeight=0;textWrappersInRow=[];maxHeightBtns=0;btnWrappersInRow=[]}
i++})}
function t778_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').each(function(e){var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');$(".r").find('a[href$="#!/tproduct/'+recid+'-'+lid_prod+'"]').click(function(e){if(rec.find('[data-product-lid='+lid_prod+']').length){rec.find('[data-product-lid='+lid_prod+'] [href^="#prodpopup"]').triggerHandler('click')}})});rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t778__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();if($(e.target).hasClass('t1002__addBtn')||$(e.target).parents().hasClass('t1002__addBtn')){return}
t778_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t778_updateSlider(recid+' #t778__product-'+lid_prod+'');setTimeout(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500)});if($('#record'+recid).length==0){t778_checkUrl(recid)}
t778_copyTypography(recid)}
function t778_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t778_updateSlider(recid){var el=$('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t778_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);$('body').addClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t778_closePopup()}});el.find('.t-popup__close, .t778__close-text').click(function(e){t778_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t778_closePopup()}})}
function t778_closePopup(){$('body').removeClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t778_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t778_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t778__title').attr('style');var descrStyle=rec.find('.t778__descr').attr('style');rec.find('.t-popup .t778__title').attr("style",t778_removeSizeStyles(titleStyle));rec.find('.t-popup .t778__descr, .t-popup .t778__text').attr("style",t778_removeSizeStyles(descrStyle))}
function t778_unifyHeights(recid){var t778_el=$('#rec'+recid),t778_blocksPerRow=t778_el.find(".t778__container").attr("data-blocks-per-row"),t778_cols=t778_el.find(".t778__textwrapper"),t778_mobScroll=t778_el.find(".t778__scroll-icon-wrapper").length;if($(window).width()<=480&&t778_mobScroll==0){t778_cols.css("height","auto");return}
var t778_perRow=+t778_blocksPerRow;if($(window).width()<=960&&t778_mobScroll>0){var t778_perRow=t778_cols.length}else{if($(window).width()<=960){var t778_perRow=2}}
for(var i=0;i<t778_cols.length;i+=t778_perRow){var t778_maxHeight=0,t778_row=t778_cols.slice(i,i+t778_perRow);t778_row.each(function(){var t778_curText=$(this).find(".t778__textwrapper"),t778_curBtns=$(this).find(".t778__btn-wrapper_absolute"),t778_itemHeight=t778_curText.outerHeight()+t778_curBtns.outerHeight();if(t778_itemHeight>t778_maxHeight){t778_maxHeight=t778_itemHeight}});t778_row.css("height",t778_maxHeight)}}
function t994_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var container=rec.querySelector('.t994__slidecontainer');var items=rec.querySelectorAll('.t994__item');var slides=rec.querySelectorAll('.t994__item-wrapper');var currentBlock=rec.querySelector('.t994');var loaders=rec.querySelectorAll('.t994__loader');var isPreview=currentBlock?currentBlock.classList.contains('t994_preview'):!1;var autoPlayInit=container?container.getAttribute('data-slider-timeout'):'0';var hasTimeout=parseFloat(autoPlayInit)>0;if(window.innerWidth>960){t994_setHeightValueForDesktop(slides,rec);var activeSlide=rec.querySelector('.t994__item.t-slds__item_active');if(!activeSlide&&items.length)items[0].classList.add('t-slds__item_active')}else{if(container)container.style.transform='translate(0, 0)';if(container)container.setAttribute('data-slide-offset','0');t994_calcHeight(rec)}
if(hasTimeout&&t994_checkVisibility(rec)){t994_initAutoPlay(rec)}
var autoPlayInitted=container?container.getAttribute('data-slider-autoplay-initted'):'';var isAutoplayInitted=autoPlayInitted==='yes';window.addEventListener('scroll',t_throttle(function(){if(hasTimeout&&t994_checkVisibility(rec)&&!isAutoplayInitted){t994_initAutoPlay(rec)}},100));if(currentBlock){currentBlock.addEventListener('displayChanged',function(){if(window.innerWidth>960)t994_setHeightValueForDesktop(slides,rec);if(container)container.style.transitionDuration='0s';if(container)container.style.transform='translate(0, 0)';if(container)container.setAttribute('data-slide-pos','0');Array.prototype.forEach.call(items,function(item){item.style.transitionDuration='0s'});t994_goToSlide(rec,0)})}
window.addEventListener('resize',function(){t994_changeHeightandOffsetOnResize(container,items);t994_calcHeight(rec)});window.addEventListener('orientationchange',function(){t994_changeHeightandOffsetOnResize(container,items);t994_calcHeight(rec)});if(isPreview||!autoPlayInit||isNaN(parseInt(autoPlayInit,10))){var pos=container?container.getAttribute('data-slide-pos'):'0';Array.prototype.forEach.call(loaders,function(loader,i){var loaderInner=loader.querySelector('.t994__loader-inner');if(i<=+pos&&loaderInner)loaderInner.style.width='100%'})}
Array.prototype.forEach.call(items,function(item,i){item.addEventListener('click',function(){t994_goToSlide(rec,i)})});var rightArrow=rec.querySelector('.t-slds__arrow_wrapper-right');var leftArrow=rec.querySelector('.t-slds__arrow_wrapper-left');if(rightArrow){rightArrow.addEventListener('click',function(){t994_slide(rec,'right')})}
if(leftArrow){leftArrow.addEventListener('click',function(){t994_slide(rec,'left')})}
Array.prototype.forEach.call(loaders,function(loader,i){loader.addEventListener('click',function(){t994_goToSlide(rec,i)})});if(!isPreview&&(!autoPlayInit||parseInt(autoPlayInit,10)===0)){var stopBtn=rec.querySelector('.t994__stopbtn');if(stopBtn)stopBtn.style.display='none'}
if(window.innerWidth<960){t994_calcHeight(rec);t_onFuncLoad('Hammer',function(){t994_initSliderSwipe(rec)})}}
function t994_changeHeightandOffsetOnResize(container,items){var pos=container?container.getAttribute('data-slide-pos'):'0';var itemWidth=items[0]?items[0].offsetWidth:0;var offset=itemWidth*pos;if(container)container.style.transitionDuration='0s';if(container)container.style.transform='translate(-'+offset+'px, 0)';Array.prototype.forEach.call(items,function(item){item.style.transitionDuration='0s'})}
function t994_setHeightValueForDesktop(slides,rec){var aspectRatio=9/16;var slideHeight=slides[0]?slides[0].offsetHeight:0;var slideWidth=slideHeight*aspectRatio;Array.prototype.forEach.call(slides,function(slide){slide.style.width=slideWidth+'px'});var slideParent=rec.querySelector('.t994__slidecontainer');var fullWidth=slides[0]?slides.length*(slideWidth+40):0;if(slideParent)slideParent.style.width=fullWidth+'px';var widthWrapper=rec.querySelector('.t994__width-wrapper');if(widthWrapper)widthWrapper.style.maxWidth=(slideWidth+40)+'px'}
function t994_checkVisibility(el){var winBottom=window.pageYOffset+window.innerHeight;var elTop=el.getBoundingClientRect().top+window.pageYOffset;return(elTop+100<=winBottom)}
function t994_calcHeight(el){var slidecontainer=el.querySelector('.t994__slidecontainer');var widthWrapper=el.querySelector('.t994__width-wrapper');var items=el.querySelectorAll('.t994__item');var itemWrappers=el.querySelectorAll('.t994__item-wrapper');if(window.isMobile){var height=document.documentElement.clientHeight;if(slidecontainer)slidecontainer.style.height=height+'px';if(widthWrapper)widthWrapper.style.height=height+'px';Array.prototype.forEach.call(items,function(item){item.style.height=height+'px'});Array.prototype.forEach.call(itemWrappers,function(wrapper){wrapper.style.height=height+'px'})}}
function t994_goToSlide(el,id){var container=el.querySelector('.t994__slidecontainer');var loaderInners=el.querySelectorAll('.t994__loader-inner');var items=el.querySelectorAll('.t994__item');var currentBlock=el.querySelector('.t994');var itemWidth=items.length?items[0].offsetWidth:0;var sliderTimeOut=container?container.getAttribute('data-slider-timeout'):'0';var sliderPos=container?container.getAttribute('data-slide-pos'):'0';var isPreview=currentBlock?currentBlock.classList.contains('t994_preview'):!1;if(+sliderPos===id)return;var allRec=document.getElementById('allrecords');var lazyMode=allRec?allRec.getAttribute('data-tilda-lazy'):'';if(window.lazy==='y'||lazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){setTimeout(t_lazyload_update(),500)})}
Array.prototype.forEach.call(items,function(item,i){i===id?item.classList.add('t-slds__item_active'):item.classList.remove('t-slds__item_active')});if(container)container.setAttribute('data-slide-pos',id);var offset=itemWidth*id;Array.prototype.forEach.call(items,function(item){item.style.transitionDuration='.3s'});if(container)container.style.transform='translate(-'+offset+'px, 0)';if(container)container.style.transitionDuration='.3s';Array.prototype.forEach.call(loaderInners,function(inner,i){inner.style.width='0';if(isPreview||isNaN(parseInt(sliderTimeOut,10))){inner.style.width=i<=id?'100%':'0'}else{inner.style.width=i<id?'100%':'0'}});if(!isPreview&&container&&container.getAttribute('data-slider-paused')==='no'){t994_playSlider(parseInt(sliderTimeOut,10),el)}
var arrowLeft=el.querySelector('.t-slds__arrow_wrapper-left');var arrowRight=el.querySelector('.t-slds__arrow_wrapper-right');switch(id){case 0:if(arrowLeft)arrowLeft.style.display='none';if(arrowRight)arrowRight.style.display='block';break;case(items.length-1):if(arrowLeft)arrowLeft.style.display='block';if(arrowRight)arrowRight.style.display='none';break;default:if(arrowLeft)arrowLeft.style.display='block';if(arrowRight)arrowRight.style.display='block';break}}
function t994_playSlider(time,el){if(el instanceof jQuery&&el.length){el=el.get(0)}
var sliderWrapper=el.querySelector('.t994__slidecontainer');var loaders=el.querySelectorAll('.t994__loader');var pos=sliderWrapper?sliderWrapper.getAttribute('data-slide-pos'):'0';var currentLoader=loaders[parseInt(pos,10)];var currentLoaderInner=currentLoader?currentLoader.querySelector('.t994__loader-inner'):null;var playBtn=el.querySelector('.t994__playbtn');var stopBtn=el.querySelector('.t994__stopbtn');if(sliderWrapper)sliderWrapper.setAttribute('data-slider-paused','no');if(playBtn)playBtn.style.display='none';if(stopBtn)stopBtn.style.display='block';if(window.t994_animateSliderBar){clearInterval(window.t994_animateSliderBar);window.t994_animateSliderBar=0}
if(time&&currentLoaderInner){t994_animateSlideBar(currentLoaderInner,time,el,pos,loaders)}}
function t994_animateSlideBar(currentLoaderInner,time,el,pos,loaders){if(currentLoaderInner.style.width==='100%'){currentLoaderInner.style.width='0'}
var increasedWidth=parseInt(currentLoaderInner.style.width,10)||0;var step=(1000-increasedWidth*10)/time;window.t994_animateSliderBar=setInterval(function(){increasedWidth+=step;currentLoaderInner.style.width=increasedWidth+'%';if(parseInt(currentLoaderInner.style.width,10)>=100){t994_slide(el,'right');if(+pos===loaders.length-1){clearInterval(window.t994_animateSliderBar);window.t994_animateSliderBar=0}}},10)}
function t994_initAutoPlay(el){var container=el.querySelector('.t994__slidecontainer');var loaders=el.querySelectorAll('.t994__loader');var playBtn=el.querySelector('.t994__playbtn');var stopBtn=el.querySelector('.t994__stopbtn');var sliderTimeOut=container?container.getAttribute('data-slider-timeout'):'0';var currentPos=container?container.getAttribute('data-slide-pos'):'0';var progress=0;t994_playSlider(parseInt(sliderTimeOut,10),el);if(stopBtn){stopBtn.addEventListener('click',function(){stopBtn.style.display='none';if(playBtn)playBtn.style.display='block';if(window.t994_animateSliderBar){clearInterval(window.t994_animateSliderBar);window.t994_animateSliderBar=0}
if(container)container.setAttribute('data-slider-paused','yes')})}
if(playBtn){playBtn.addEventListener('click',function(){playBtn.style.display='none';if(stopBtn)stopBtn.style.display='block';currentPos=container?container.getAttribute('data-slide-pos'):'0';var currentLoader=loaders[parseInt(currentPos,10)];var loaderWidth=currentLoader?currentLoader.offsetWidth:0;var currentLoaderInner=currentLoader?currentLoader.querySelector('.t994__loader-inner'):null;progress=currentLoaderInner?currentLoaderInner.offsetWidth:0;t994_playSlider(sliderTimeOut-(progress/loaderWidth*sliderTimeOut),el);if(container)container.setAttribute('data-slider-paused','no')})}
if(window.innerWidth<960&&container){container.addEventListener('touchstart',function(e){if(window.t994_animateSliderBar){clearInterval(window.t994_animateSliderBar);window.t994_animateSliderBar=0}
if(e.target.classList.contains('t994__title')||e.target.classList.contains('t994__descr')){e.target.classList.add('t994__txt-selectable')}});container.addEventListener('touchend',function(){var allText=document.querySelectorAll('.t994__title, .t994__descr');Array.prototype.forEach.call(allText,function(text){text.classList.remove('t994__txt-selectable')});currentPos=container?container.getAttribute('data-slide-pos'):'0';var currentLoader=loaders[parseInt(currentPos,10)];var curLoaderInner=currentLoader?currentLoader.querySelector('.t994__loader-inner'):null;var curLoaderWidth=currentLoader?currentLoader.offsetWidth:0;progress=curLoaderInner?curLoaderInner.offsetWidth:0;t994_playSlider(sliderTimeOut-(progress/curLoaderWidth*sliderTimeOut),el)})}
container.setAttribute('data-slider-autoplay-initted','yes')}
function t994_slide(el,direction){var container=el.querySelector('.t994__slidecontainer');var loaders=el.querySelectorAll('.t994__loader');var items=el.querySelectorAll('.t994__item');var currentBlock=el.querySelector('.t994');var arrowsWrapperLeft=el.querySelectorAll('.t-slds__arrow_wrapper-left');var arrowsWrapperRight=el.querySelectorAll('.t-slds__arrow_wrapper-right');var sliderTimeOut=container?container.getAttribute('data-slider-timeout'):'0';var currentPos=container?container.getAttribute('data-slide-pos'):'0';var loaderPos=sliderTimeOut>0?+currentPos:+currentPos+1;var isPreview=currentBlock?currentBlock.classList.contains('t994_preview'):!1;var currentLoader=loaders[loaderPos];var currentLoaderInner=currentLoader?currentLoader.querySelector('.t994__loader-inner'):null;var sliderLeftPos=container?container.getAttribute('data-slide-offset'):'0';var itemWidth=items[0]?items[0].offsetWidth:0;switch(direction){case 'right':if(currentPos>=items.length-1)return;Array.prototype.forEach.call(arrowsWrapperLeft,function(arrowWrapperLeft){arrowWrapperLeft.style.display='block'});if(currentLoaderInner)currentLoaderInner.style.width='100%';if(container)container.setAttribute('data-slide-pos',++currentPos);break;case 'left':Array.prototype.forEach.call(arrowsWrapperRight,function(arrowWrapperRight){arrowWrapperRight.style.display='block'});if(currentLoaderInner)currentLoaderInner.style.width='0';if(container)container.setAttribute('data-slide-pos',--currentPos);var prevLoader=loaders[loaderPos-1];var prevLoaderInner=prevLoader?prevLoader.querySelector('.t994__loader-inner'):null;if(prevLoaderInner)prevLoaderInner.style.width='0';if(currentPos<0||loaderPos<0)return;break}
switch(+currentPos){case 0:Array.prototype.forEach.call(arrowsWrapperLeft,function(wrapLeft){wrapLeft.style.display='none'});break;case(items.length-1):Array.prototype.forEach.call(arrowsWrapperRight,function(wrapRight){wrapRight.style.display='none'});break}
Array.prototype.forEach.call(items,function(item,i){if(i===+currentPos){item.classList.add('t-slds__item_active')}else{item.classList.remove('t-slds__item_active')}
item.style.transitionDuration='.3s'});var offset=sliderLeftPos-itemWidth*currentPos;if(container)container.style.transform='translate('+offset+'px, 0)';if(container)container.style.transitionDuration='.3s';if(!isPreview&&parseInt(sliderTimeOut,10)>0&&container&&container.getAttribute('data-slider-paused')==='no'){t994_playSlider(parseInt(sliderTimeOut,10),el)}
var allRec=document.getElementById('allrecords');var lazyMode=allRec?allRec.getAttribute('data-tilda-lazy'):'';if(window.lazy==='y'||lazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t994_initSliderSwipe(el){var sliderWrapper=el.querySelector('.t994__slidecontainer');var totalSlides=el.querySelectorAll('.t994__item').length;var timeout;var isScrolling=!1;delete Hammer.defaults.cssProps.userSelect;var hammer=new Hammer(sliderWrapper,{domEvents:!0,inputClass:Hammer.TouchInput,recognizers:[[Hammer.Pan,{direction:Hammer.DIRECTION_HORIZONTAL,}],],});window.addEventListener('scroll',function(){isScrolling=!0;clearTimeout(timeout);timeout=setTimeout(function(){isScrolling=!1},250)});if(totalSlides===1)return!1;hammer.on('pan',function(event){if(isScrolling){return!1}
var sliderWrapper=el.querySelector('.t994__slidecontainer');sliderWrapper.setAttribute('data-slider-touch','yes');if(event.isFinal){if(event.velocityX>0.4){t994_slide(el,'left')}else if(event.velocityX<-0.4){t994_slide(el,'right')}
sliderWrapper.setAttribute('data-slider-touch','')}})}